"""
T11 - The hybrid briefing system.
A LangGraph spine that delegates to autonomous (Phase 2) and
orchestrator (Phase 3) sub-agents at specific nodes.
"""

import sys
from datetime import datetime
from typing import TypedDict
from langgraph.graph import StateGraph, START, END

# Import from tutorial-10 - reusing what we built last week
sys.path.insert(0, "../tutorial-10")
from agent_loop import run_agent
from gold_tools import (
    get_gold_price,
    GOLD_TOOLS,
    execute_gold_tool,
)
from bull_analyst import consult_bull_analyst
from bear_analyst import consult_bear_analyst

from anthropic import Anthropic
client = Anthropic()


# -----------------------------------------------------------
# THE STATE - one field per briefing section
# -----------------------------------------------------------

class BriefingState(TypedDict):
    """The shared state passed between briefing nodes.
    Each section of the briefing lives in its own field.
    Nodes return only the field(s) they populate."""
    header: str
    current_state: str
    week_movement: str
    bull_view: str
    bear_view: str
    consensus: str
    footer: str
    
# -----------------------------------------------------------
# CONTROLLED NODES (Phase 1) - no LLM, just formatting
# -----------------------------------------------------------

def header_node(state: BriefingState) -> dict:
    """Generate the briefing header with today's date."""
    print("[spine] header_node")
    today = datetime.now().strftime("%B %d, %Y")
    return {"header": f"# Weekly Gold Market Briefing - {today}\n"}


def footer_node(state: BriefingState) -> dict:
    """Generate the briefing footer."""
    print("[spine] footer_node")
    return {"footer": "\n---\nGenerated by your AI Orchestration system.\n"}
    
# -----------------------------------------------------------
# CURRENT STATE - Phase 1 with a tool call
# -----------------------------------------------------------

def current_state_node(state: BriefingState) -> dict:
    """Fetch the current gold price and format it for the briefing."""
    print("[spine] current_state_node - fetching live price")
    price_data = get_gold_price()
    formatted = f"## Current State\n\n{price_data}\n"
    return {"current_state": formatted}
    
# -----------------------------------------------------------
# WEEK'S MOVEMENT - Phase 2 autonomous agent
# -----------------------------------------------------------

INVESTIGATION_PROMPT = """You are a gold market reporter. Your job is to
investigate this week's gold price action and write a paragraph for a weekly
briefing.

You have access to gold price tools. Use them to gather facts. Look at the
current price, the previous close, the day's range, and any other data
points you can extract. Reason about what's notable.

Write 3-5 sentences for the briefing. Be specific about numbers. Note the
day's move, the trading range, and one observation about what the data
suggests. Do not invent figures - only cite what the tools return."""


def week_movement_node(state: BriefingState) -> dict:
    """Run an autonomous agent to investigate the week's movement."""
    print("[spine] week_movement_node - delegating to autonomous agent")
    summary = run_agent(
        system_prompt=INVESTIGATION_PROMPT,
        user_query="Investigate this week's gold price action and write the paragraph.",
        tools=GOLD_TOOLS,
        tool_executor=execute_gold_tool,
        label="investigator",
    )
    formatted = f"## This Week's Movement\n\n{summary}\n"
    return {"week_movement": formatted}
    
# -----------------------------------------------------------
# BULL & BEAR VIEWS - Phase 3 sub-agents reused from T10
# -----------------------------------------------------------

def bull_view_node(state: BriefingState) -> dict:
    """Delegate to T10's bull analyst sub-agent."""
    print("[spine] bull_view_node - consulting bull analyst")
    bull_argument = consult_bull_analyst(
        "Looking at current gold prices, what is the strongest case for buying gold this week?"
    )
    formatted = f"## Bull View\n\n{bull_argument}\n"
    return {"bull_view": formatted}


def bear_view_node(state: BriefingState) -> dict:
    """Delegate to T10's bear analyst sub-agent."""
    print("[spine] bear_view_node - consulting bear analyst")
    bear_argument = consult_bear_analyst(
        "Looking at current gold prices, what is the strongest case against buying gold this week?"
    )
    formatted = f"## Bear View\n\n{bear_argument}\n"
    return {"bear_view": formatted}
    
# -----------------------------------------------------------
# CONSENSUS - Phase 1 with one synthesis LLM call
# -----------------------------------------------------------

CONSENSUS_PROMPT = """You are writing the consensus section of a weekly gold
market briefing. You have already received:
  - The current price data
  - This week's price action summary
  - A bull analyst's argument
  - A bear analyst's argument

Your job is to write a balanced 3-4 sentence consensus paragraph that names
the strongest point on each side, identifies where bull and bear agree,
and offers a measured conclusion.

Do not introduce new facts. Synthesise only what the prior sections contain.
Do not give investment advice.

Output format: write the paragraph directly. Do not include a heading,
title, or section marker - the surrounding system adds those."""


def consensus_node(state: BriefingState) -> dict:
    """Synthesise a balanced consensus from all preceding sections."""
    print("[spine] consensus_node - synthesising")

    inputs = (
        f"{state['current_state']}\n"
        f"{state['week_movement']}\n"
        f"{state['bull_view']}\n"
        f"{state['bear_view']}\n"
    )

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=600,
        system=CONSENSUS_PROMPT,
        messages=[{"role": "user", "content": inputs}],
    )

    consensus_text = response.content[0].text
    formatted = f"## Consensus\n\n{consensus_text}\n"
    return {"consensus": formatted}
    
# -----------------------------------------------------------
# THE GRAPH - sequential spine, START to END
# -----------------------------------------------------------

graph = StateGraph(BriefingState)

graph.add_node("header", header_node)
graph.add_node("current_state", current_state_node)
graph.add_node("week_movement", week_movement_node)
graph.add_node("bull_view", bull_view_node)
graph.add_node("bear_view", bear_view_node)
graph.add_node("consensus", consensus_node)
graph.add_node("footer", footer_node)

# Sequential flow - each node depends on the previous having run
graph.add_edge(START, "header")
graph.add_edge("header", "current_state")
graph.add_edge("current_state", "week_movement")
graph.add_edge("week_movement", "bull_view")
graph.add_edge("bull_view", "bear_view")
graph.add_edge("bear_view", "consensus")
graph.add_edge("consensus", "footer")
graph.add_edge("footer", END)

briefing_app = graph.compile()


# -----------------------------------------------------------
# PUBLIC INTERFACE - generate a complete briefing
# -----------------------------------------------------------

def generate_briefing() -> str:
    """Run the briefing pipeline and return the complete markdown document."""
    initial_state = BriefingState(
        header="",
        current_state="",
        week_movement="",
        bull_view="",
        bear_view="",
        consensus="",
        footer="",
    )

    final_state = briefing_app.invoke(initial_state)

    # Stitch the sections together in order
    return (
        final_state["header"]
        + final_state["current_state"]
        + final_state["week_movement"]
        + final_state["bull_view"]
        + final_state["bear_view"]
        + final_state["consensus"]
        + final_state["footer"]
    )